---
name: Build and Push Container

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g., v1.0.0, latest, pr-123)'
        required: true
        type: string
      push_to_registry:
        description: 'Whether to push to registry'
        required: false
        type: boolean
        default: true
      source_ref:
        description: 'Git ref to build from'
        required: false
        type: string
        default: 'main'
    outputs:
      image_url:
        description: 'Full image URL'
        value: ${{ jobs.build.outputs.image_url }}

  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch to build from'
        required: true
        type: string
        default: 'main'
      image_tag:
        description: 'Docker image tag (e.g., v1.0.0, test-branch, latest)'
        required: true
        type: string
      push_to_registry:
        description: 'Whether to push to registry'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.meta.outputs.tags }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source_ref || inputs.source_branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: ${{ inputs.push_to_registry }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/serenemind-io
          tags: |
            type=raw,value=${{ inputs.image_tag }}
          labels: |
            org.opencontainers.image.title=Serenemind.io
            org.opencontainers.image.description=Built with Django and Alpine.js
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: ${{ inputs.push_to_registry }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Output summary
        run: |
          echo "Container build completed!"
          echo "Image: ${{ steps.meta.outputs.tags }}"
          echo "Source: ${{ inputs.source_ref || inputs.source_branch }}"
          echo "Pushed to registry: ${{ inputs.push_to_registry }}"
